name: maplinrobotarm
version: 1.0.3
vendor: Maarten Ectors <maarten@ectors.com>
icon: meta/maplin.svg
services:
 - name: maplinrobotarm
   start: bin/maplinrobotarm
 - name: maplinrobotarmweb
   start: bin/maplinrobotarmweb
integration:
  maplinrobotarm:
    apparmor: meta/maplinrobotarm.apparmor
ports:
  required: 8787,3000
