name: maplin-robot-arm
version: 1.0.0
vendor: Maarten Ectors <maarten@ectors.com>
icon: meta/maplin.svg
services:
 - name: robot-backend
   start: bin/maplinrobotarm
 - name: robot-frontend
   start: bin/maplinrobotarmweb
integration:
    maplin-robot-arm:
        apparmor: meta/maplin-robot-arm.apparmor
ports:
 required: 8787,3000
